export enum TrackOrder {
  Relevance = 'relevance',
  Buzzrate = 'buzzrate',
  DownloadsWeek = 'downloads_week',
  DownloadsMonth = 'downloads_month',
  DownloadsTotal = 'downloads_total',
  ListensWeek = 'listens_week',
  ListensMonth = 'listens_month',
  ListensTotal = 'listens_total',
  PopularityWeek = 'popularity_week',
  PopularityMonth = 'popularity_month',
  PopularityTotal = 'popularity_total',
  Name = 'name',
  AlbumName = 'album_name',
  ArtistName = 'artist_name',
  ReleaseDate = 'releasedate',
  ReleaseDateDesc = 'releasedate_desc',
  Duration = 'duration',
  Id = 'id',
}
